apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: webapi1 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapi1 
    spec:
      containers:
        - name: webapi1 
          image: sgreenacr.azurecr.io/webapi1 
          ports:
          - containerPort: 80