apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: webapidemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapidemo 
    spec:
      containers:
        - name: webapidemo 
          image: sgreenacr.azurecr.io/webapidemo 
          ports:
          - containerPort: 80